version: '3.4'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - app_data:/app/upload
    ports:
     - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongodb
    volumes:
      - db_data:/data/db

volumes:
  app_data
  db_data
  